version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci
  
  pre_build:
    commands:
      - echo "Running pre-build checks..."
      - echo "Node version:" && node --version
      - echo "NPM version:" && npm --version
      - echo "Listing source files..."
      - ls -la src/
  
  build:
    commands:
      - echo "Building the application..."
      - npm run build
      - echo "Build completed successfully"
      - echo "Listing build output..."
      - ls -la dist/
  
  post_build:
    commands:
      - echo "Post-build phase..."
      - echo "Build artifacts ready for deployment"

artifacts:
  files:
    - 'dist/**/*'
    - 'node_modules/**/*'
    - 'package.json'
    - 'package-lock.json'
  name: temp-demo-build-$(date +%Y-%m-%d-%H-%M-%S)

cache:
  paths:
    - 'node_modules/**/*'
